# Generated by Django 4.0.4 on 2022-04-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
