# Generated by Django 4.0.4 on 2022-04-14 09:49

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_taskimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskImage',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.filepath),
        ),
    ]
