# Generated by Django 4.0.4 on 2022-04-14 12:07

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_task_taskimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskImage', models.ImageField(blank=True, null=True, upload_to=home.models.filepath)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
