# Generated by Django 4.0.4 on 2022-04-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_gifcon'),
    ]

    operations = [
        migrations.CreateModel(
            name='translan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskDesc', models.TextField()),
                ('taskLan', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
